force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object represents a Meetup event that Users can register to.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A random code that is used to locate the Meetup on the Registration Page.</description>
    <inlineHelpText>Do not enter a value. A unique code will be generated automatically.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations allowed for this Meetup.</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>When the Status is Open new registrations will be allowed.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>This holds details about a single registration to a Meetup.</description>
    <label>MeetupRegistration</label>
    <nameField>
        <displayFormat>RN-{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MeetupRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The registered party&apos;s email address.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>The registered party&apos;s first name.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>The registered party&apos;s last name.</description>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The relationship with the parent Meetup object.</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>MeetupRegistrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController.cls
public with sharing class MeetupRegistrationController {
  @AuraEnabled
  public static MeetupRegistration__c saveRegistration(String firstName, String lastName, string email, string code) {
      MeetupRegistration__c newRegistration = new MeetupRegistration__c();

      Meetup__c meetup = findMeetup(code);

      ID meetupId = meetup.ID;
      
      if (meetup.Status__c == 'Closed' || isMeetupFull(meetup)) {
        String message = 'This Meetup is full or closed!';
        AuraHandledException error = new AuraHandledException(message);
        error.setMessage(message);
        throw error;
      } else if (isEmailAlreadyRegistered(meetupId, email)) {
        String message = 'This email is already registered to this event!';
        AuraHandledException error = new AuraHandledException(message);
        error.setMessage(message);
        throw error;
      } else {
        newRegistration.FirstName__c = firstName;
        newRegistration.LastName__c = lastName;
        newRegistration.Email__c = email;
        newRegistration.Meetup__c = meetupId;

        insert newRegistration;
      }
      
      closeMeetupIfFull(meetup);

      return newRegistration;
  }

  private static Meetup__C findMeetup(String code) {
    Meetup__c meetup = [
      SELECT Id, Status__c, RegistrationLimit__c, Name 
      FROM Meetup__c 
      WHERE RegistrationCode__c = :code
    ];
    return meetup;
  }
  
  // Check for duplicate emails
  private static Boolean isEmailAlreadyRegistered(ID meetupId, String email) {
    List<MeetupRegistration__c> registrationsWithEmail = [
      SELECT Id
      FROM MeetupRegistration__c
      WHERE Meetup__c = :meetupId
      AND Email__c = :email
    ];

    return registrationsWithEmail.size() > 0;
  }
  
  // Automatically close event if full
  private static void closeMeetupIfFull(Meetup__c meetup) {
    if (isMeetupFull(meetup)) {
      meetup.Status__c = 'Closed';
      update meetup;
    }
  }

  private static Boolean isMeetupFull(Meetup__c meetup) {
    ID meetupId = meetup.Id;
    Integer registrationLimit = meetup.RegistrationLimit__c.intValue();

    List<MeetupRegistration__c> allRegistrations = [
      SELECT Id
      FROM MeetupRegistration__c
      WHERE Meetup__c = :meetupId
    ];
    
    Integer currentRegistrations = allRegistrations.size();

    Return currentRegistrations >= registrationLimit;
  }
}