force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>This object represents a Meetup event that Users can register to.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A random code that is used to locate the Meetup on the Registration Page.</description>
    <inlineHelpText>Do not enter a value. A unique code will be generated automatically.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations allowed for this Meetup.</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>This holds details about a single registration to a Meetup.</description>
    <label>MeetupRegistration</label>
    <nameField>
        <displayFormat>RN-{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MeetupRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>The registered party&apos;s first name.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The relationship with the parent Meetup object.</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>MeetupRegistrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestMeetupRegistrationController.cls
@isTest 
public class TestMeetupRegistrationController {
    @isTest static void successfulSaveRegistration() {
      Meetup__c meetup = new Meetup__c(
                             Name = 'Test Meetup',
                             RegistrationLimit__c = 3);
      insert meetup;
      
      Meetup__c newMeetup = [
        SELECT Id, RegistrationCode__c
        FROM Meetup__c
        WHERE Name = 'Test Meetup'
        LIMIT 1
      ];

      String registrationCode = newMeetup.RegistrationCode__c;
      ID meetupId = newMeetup.Id;
      
      MeetupRegistration__c newRegistration = MeetupRegistrationController.saveRegistration('Steve', 'Meyers', 'sm@gmail.com', registrationCode);

      List<MeetupRegistration__c> registrationsCreated = [
        SELECT Id, FirstName__c
        FROM MeetupRegistration__c
        WHERE Meetup__c = :meetupId
      ];

      System.assertEquals(1, registrationsCreated.size());
      System.assertEquals('Steve', registrationsCreated[0].FirstName__c);
    }

    @isTest static void duplicateEmailRegistrationTest() {
      Meetup__c meetup = new Meetup__c(
        Name = 'Test Meetup',
        RegistrationLimit__c = 3);
        insert meetup;

        Meetup__c newMeetup = [
          SELECT Id, RegistrationCode__c
          FROM Meetup__c
          WHERE Name = 'Test Meetup'
          LIMIT 1
        ];
  
        String registrationCode = newMeetup.RegistrationCode__c;
        ID meetupId = newMeetup.Id;

        MeetupRegistrationController.saveRegistration('Steve', 'Meyers', 'sm@gmail.com', registrationCode);
        try {
          MeetupRegistrationController.saveRegistration('Doppel', 'Ganger', 'sm@gmail.com', registrationCode);
        } catch (AuraHandledException e) {
          System.assertEquals('This email is already registered to this event!', e.getMessage());
        }
    }

    @isTest static void closedMeetupRegistrationTest() {
      Meetup__c meetup = new Meetup__c(
        Name = 'Test Meetup',
        RegistrationLimit__c = 1);
        insert meetup;

        Meetup__c newMeetup = [
          SELECT Id, RegistrationCode__c
          FROM Meetup__c
          WHERE Name = 'Test Meetup'
          LIMIT 1
        ];
  
        String registrationCode = newMeetup.RegistrationCode__c;
        ID meetupId = newMeetup.Id;

        MeetupRegistrationController.saveRegistration('Steve', 'Meyers', 'sm@gmail.com', registrationCode);
        try {
          MeetupRegistrationController.saveRegistration('Taylor', 'Myers', 'tm@gmail.com', registrationCode);
        } catch (AuraHandledException e) {
          System.assertEquals('This Meetup is full or closed!', e.getMessage());
        }
    }
}